# fly.toml app configuration file generated for max-ai on 2023-06-07T18:13:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "max-ai"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "15s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "sjc"

[[mounts]]
  source = "slack_data"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
