global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis-1'
    static_configs:
      - targets: ['redis-exporter-1:9121']

  - job_name: 'redis-2'
    static_configs:
      - targets: ['redis-exporter-2:9121']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
