apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: d29yZHByb3N0  # Base64 encoded value of 'wordpress'
  MYSQL_DATABASE: d29yZHByb3N0  # Base64 encoded value of 'wordpress'
  MYSQL_USER: d29yZHByb3N0  # Base64 encoded value of 'wordpress'
  MYSQL_PASSWORD: d29yZHByb3N0  # Base64 encoded value of 'wordpress'